punit:
  service.factoryPid:                       "gemini.jpa.punit"
  gemini.jpa.punit.name:                    "Blog"
  eclipselink.target-database:              "MySQL"

  javax.persistence.jdbc.driver:            "com.mysql.jdbc.Driver"
  javax.persistence.jdbc.url:               "jdbc:mysql://localhost:3306/osgi"
  javax.persistence.jdbc.user:              "osgi"
  javax.persistence.jdbc.password:          "osgi"

  eclipselink.logging.logger:               "JavaLogger"
  eclipselink.logging.level.sql:            "FINE"
  eclipselink.logging.level:                "FINE"
  eclipselink.logging.timestamp:            "false"
  eclipselink.logging.thread:               "false"
  eclipselink.logging.exceptions:           "true"

  eclipselink.orm.throw.exceptions:         "true"
  eclipselink.jdbc.read-connections.min:    "1"
  eclipselink.jdbc.write-connections.min:   "1"
  eclipselink.ddl-generation:               "drop-and-create-tables"
  eclipselink.weaving:                      "true"

